2025-04-23 10:28:51.962 | ERROR    | __main__:check_service:53 - http://datavalidator.fake | ERROR: ClientConnectorDNSError(ConnectionKey(host='datavalidator.fake', port=80, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(-2, 'Name or service not known'))
2025-04-23 10:28:51.962 | ERROR    | __main__:check_service:53 - http://formit.fake | ERROR: ClientConnectorDNSError(ConnectionKey(host='formit.fake', port=80, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(-2, 'Name or service not known'))
2025-04-23 10:28:51.962 | ERROR    | __main__:check_service:53 - http://bitdashboard.fake | ERROR: ClientConnectorDNSError(ConnectionKey(host='bitdashboard.fake', port=80, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(-2, 'Name or service not known'))
2025-04-23 10:28:51.963 | ERROR    | __main__:check_service:53 - http://leadsync.fake | ERROR: ClientConnectorDNSError(ConnectionKey(host='leadsync.fake', port=80, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(-2, 'Name or service not known'))
2025-04-23 10:28:52.052 | INFO     | __main__:check_service:27 - https://api.rewora.ru/projects/1 | 405 | 0.10s
2025-04-23 10:33:52.154 | ERROR    | __main__:check_service:53 - http://leadsync.fake | ERROR: ClientConnectorDNSError(ConnectionKey(host='leadsync.fake', port=80, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(-2, 'Name or service not known'))
2025-04-23 10:33:52.158 | ERROR    | __main__:check_service:53 - http://formit.fake | ERROR: ClientConnectorDNSError(ConnectionKey(host='formit.fake', port=80, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(-2, 'Name or service not known'))
2025-04-23 10:33:52.158 | ERROR    | __main__:check_service:53 - http://datavalidator.fake | ERROR: ClientConnectorDNSError(ConnectionKey(host='datavalidator.fake', port=80, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(-2, 'Name or service not known'))
2025-04-23 10:33:52.158 | ERROR    | __main__:check_service:53 - http://bitdashboard.fake | ERROR: ClientConnectorDNSError(ConnectionKey(host='bitdashboard.fake', port=80, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(-2, 'Name or service not known'))
2025-04-23 10:33:52.159 | INFO     | __main__:check_service:27 - https://api.rewora.ru/projects/1 | 405 | 0.01s
